### ISSUE TITLE
Serial Read fail

### ISSUE THREAD

**Issue by mazter00** [mazter00/urdal#2]
pi@elv:~/pyscript $ python3 sread.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sread.py", line 16, in <module>
    a = sport.readline().rstrip()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 497, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by mazter00** [comment]
Ensure only one terminal is running the script at any time. No additional code will be added to fix or check for this spesific issue.
