### ISSUE TITLE
Cannot import matplotlib

### ISSUE THREAD

**Issue by MortenAlnius** [mazter00/urdal#3]
pi@elv:~/pyscript $ python3 plotting.py 
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "plotting.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/path.py", line 26, in <module>
    from . import _path, rcParams
ImportError: numpy.core.multiarray failed to import

**Comment by MortenAlnius** [comment]
Using pi@elv:~/pyscript $ python3 -m pip install numpy -v

will install it in just under 10 minutes. Won't fix the issue, just creates new ones.

**Comment by MortenAlnius** [comment]
https://stackoverflow.com/questions/44272733/cant-import-matplotlib-pyplot-as-plt

Final solution. Should be top on Google, but it isn't.
